const strings = {
  firstStep: "Choosing a path",
  secondStep: "Choosing a date",
  thirdStep: "Flight selection",
  fourthStep: "Who's coming?",
  fifthStep: "Tickets summary",
  from: "From",
  to: "To",
  submit: "Submit",
  roundTrip: "Round-trip",
  oneWay: "One-way",
  selectDate: "Select date: ",
  adult: "adult",
  childrens: "childrens",
  infants: "infants",
  summary: "Summary",
  departureAt: "Departure date and time: ",
  returnAt: "Date of return departure: ",
  passengers: "Passengers: ",
  Adult: "Adult: ",
  Childrens: "Childrens: ",
  Infants: "Infants: ",
  buy: "Buy",
};

export default strings;
